config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end

  resources :bookmarks, only: :index
  resources :hashtags, only: [:index, :show], path: 'explore'

  resources :message_threads, only: :index, path: '/messages' do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  get '/dashboard', to: 'dashboard#index'
  get '/profile', to: 'profiles#show'
  put '/profile', to: 'profiles#update'

  resources :usernames, only: [ :new, :update ]
  resources :users, only: :show do
    resources :followings, only: [ :create, :destroy]
  end

  resources :notifications, only: :index
  get 'notifications/delete_all'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  HASHTAG_REGEX = /(#\w+)/
  MENTION_REGEX = /(@\w+)/

  belongs_to :user
  validates :body, presence: true, length: { maximum: 280 }
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :retweets, dependent: :destroy
  has_many :retweeted_users, through: :retweets, source: :user
  has_many :views
  has_many :viewed_users, through: :views, source: :user
  belongs_to  :parent_tweet, 
              inverse_of: :reply_tweets, 
              foreign_key: :parent_tweet_id, 
              class_name: "Tweet", 
              optional: true,
              counter_cache: :reply_tweets_count
  has_many :reply_tweets, foreign_key: :parent_tweet_id, class_name: "Tweet", dependent: :destroy
  has_many :replied_tweets_users, through: :reply_tweets, source: :user
  has_and_belongs_to_many :hashtags
  has_many :mentions, dependent: :destroy
  has_many :mentioned_users, through: :mentions

  before_save :parse_and_save_hashtags

  def parse_and_save_hashtags
    matches = body.scan(HASHTAG_REGEX)
    return if matches.empty?

    matches.flatten.each do |tag|
      hashtag = Hashtag.find_or_create_by(tag: tag.delete("#"))
      hashtags << Hashtag.find_or_create_by(tag: tag.delete("#"))
    end
  end

  after_save :parse_and_save_mentions

  def parse_and_save_mentions
    matches = body.scan(MENTION_REGEX)
    return if matches.empty?

    matches.flatten.each do |mention|
      mentioned_user = User.find_by(username: mention.delete("@"))
      next if mentioned_user.blank?

      next if mentions.exists?(mentioned_user: mentioned_user)

      mentions.create(mentioned_user: mentioned_user)
      Notification.create(user: mentioned_user, actor: user, verb: "mentioned-me", tweet: self)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!

    def show
        ViewTweetJob.perform_later(tweet: tweet, user: current_user)
        @tweet_presenter = TweetPresenter.new(tweet: tweet, current_user: current_user)
        @reply_tweets_in_presenter = tweet.reply_tweets.includes(:liked_users, :bookmarked_users, :retweeted_users, :user).order(created_at: :desc).map do |reply_tweet|
            TweetPresenter.new(tweet: reply_tweet, current_user: current_user)
        end
    end

    def create
        @tweet = Tweet.create(tweet_params.merge(user: current_user))

        TweetActivity::TweetedJob.perform_later(actor: current_user, tweet: @tweet)

        if @tweet.persisted?
            respond_to do |format|
                format.html {redirect_to dashboard_url}
                format.turbo_stream
            end
        end
    end

    private

    def tweet_params
        params.require(:tweet).permit(:body)
    end

    def tweet
        @tweet ||= Tweet.find(params[:id]) 
    end

    # def create_view_record
    #     View.create(tweet: tweet, user: current_user)
    # end
end

app/views/tweets/_show_stats.html.erb
<div id="tweet_stats">
    <%#= @tweet_presenter.tweet.liked_users.pluck(:username) %>
    <div class="d-flex justify-content-start mb-4">
        <div class="me-4"><span class="fw-bold"><%= tweet_presenter.views_count %></span> Views</div>
        <div class="me-4"><span class="fw-bold"><%= tweet_presenter.reply_tweets_count %></span> Replies</div>
        <div class="me-4"><span class="fw-bold"><%= tweet_presenter.retweets_count %></span> Retweets</div>
        <div class="me-4"><span class="fw-bold"><%= tweet_presenter.likes_count %></span> Likes</div>
    </div>

    <div class="d-flex justify-content-evenly align-items-center action-links">
        <div>
            <%= link_to "#", class: "text-decoration-none text-black views" do %>
                <%= image_tag "bar-graph.png", size: "24x24", class: "me-1" %>
                
            <% end %>
        </div>
        <div>
            <%= link_to tweet_path(tweet_presenter.tweet), class: "text-decoration-none text-black replies" do %>
                <%= image_tag "speech-bubble.png", size: "24x24", class: "me-1" %>
                
            <% end %>
        </div>
        <div>
            <%= link_to tweet_presenter.retweet_tweet_url(source: "tweet_show"), data: { "turbo-method": tweet_presenter.turbo_retweet_data_method }, class: "text-decoration-none text-black retweets" do %>
                <%= image_tag tweet_presenter.retweet_image, size: "24x24", class: "me-1" %>
            <% end %>
        </div>
        <div>
            <%= link_to tweet_presenter.like_tweet_url(source: "tweet_show"), data: { "turbo-method": tweet_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do %>
                <%= image_tag tweet_presenter.like_image, size: "24x24", class: "me-1" %>
            <% end %>
        </div>
        <div>
            <%= link_to tweet_presenter.bookmark_tweet_url(source: "tweet_show"), data: { "turbo-method": tweet_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black bookmarks" do %>
                <%= image_tag tweet_presenter.bookmark_image, size: "24x24", class: "me-1" %>
            <% end %>
        </div>
    </div>
</div>

app/views/tweets/_tweet.html.erb
<% if tweet_presenter.render_tweet_activity? %>
    <%= sanitize(tweet_presenter.tweet_activity_html) %>
<% end %>
<%= turbo_frame_tag dom_id(tweet_presenter.tweet) do %>

    <div data-controller="tweet-card" data-tweet-path="<%= tweet_path(tweet_presenter.tweet) %>" class="tweet py-3 px-3 d-flex hover">
        <div class="flex-shrink-0">
            <%= image_tag tweet_presenter.avatar, size: "50x50", class: "rounded-circle" %>
        </div>
        <div class="flex-grow-1 ms-3">
            <p class="mb-0"><span class="fw-bolder"><%= tweet_presenter.display_name %> </span> <span class="text-muted">@<%= tweet_presenter.username %></span> · <%= tweet_presenter.created_at %></p>
            <%= sanitize(tweet_presenter.body_html) %>

            <div class="d-flex justify-content-between align-items-center action-links">
                <div>
                    <%= link_to "#", data: { "ignore-click":true }, class: "text-decoration-none text-black views" do %>
                        <%= image_tag "bar-graph.png", size: "20x20", class: "me-1" %>
                        <span><%= tweet_presenter.views_count %></span>
                    <% end %>
                </div>
                <div>
                    <%= link_to tweet_path(tweet_presenter.tweet), data: { "ignore-click":true }, class: "text-decoration-none text-black replies" do %>
                        <%= image_tag "speech-bubble.png", size: "20x20", class: "me-1" %>
                        <span><%= tweet_presenter.reply_tweets_count %> </span>
                    <% end %>
                </div>
                <div>
                    <%= link_to tweet_presenter.retweet_tweet_url, data: { "ignore-click":true, "turbo-method": tweet_presenter.turbo_retweet_data_method }, class: "text-decoration-none text-black retweets" do %>
                        <%= image_tag tweet_presenter.retweet_image, size: "20x20", class: "me-1" %>
                        <span><%= tweet_presenter.retweets_count %></span>
                    <% end %>
                </div>
                <div>
                    <%= link_to tweet_presenter.like_tweet_url, data: { "ignore-click":true, "turbo-method": tweet_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do %>
                        <%= image_tag tweet_presenter.like_image, size: "20x20", class: "me-1" %>
                        <span><%= tweet_presenter.likes_count %></span>
                    <% end %>
                </div>
                <div>
                    <%= link_to tweet_presenter.bookmark_tweet_url, data: { "ignore-click":true, "turbo-method": tweet_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black bookmarks" do %>
                        <%= image_tag tweet_presenter.bookmark_image, size: "20x20", class: "me-1" %>
                        <span><%= tweet_presenter.bookmark_text %></span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>

<%# if tweet_presenter.tweet.parent_tweet_id.present? %>
    <%# current_user.tweet_activities.where(verb: "replied", tweet: tweet_presenter.tweet).each do |tweet_activity| %>
        <%#= tweet_activity.tweet.parent_tweet.body %>
    <%# end %>
<%# end %>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
    <%= render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(tweet: @tweet, current_user: current_user) } %>
<% end %>

app/views/tweets/show.html.erb
<div class="col-7">
    <div class="mb-3">
        <%= link_to :back, class: "fs-4 text-decoration-none text-black fw-semibold" do %>
            <%= image_tag "back.png", size: "28x28", class: "me-4" %>
            <span style="position:relative; top: 2px;">Tweet</span>
        <% end %>

        <div data-tweet-path="<%= tweet_path(@tweet_presenter.tweet) %>" class="tweet py-3 px-3 d-flex">
            <div class="flex-shrink-0">
                <%= link_to image_tag(@tweet_presenter.avatar, size: "50x50", class: "rounded-circle"), user_path(@tweet_presenter.user) %>
            </div>
            <div class="flex-grow-1 ms-3">
                <p class="fw-bolder mb-0"><%= @tweet_presenter.display_name %></p>
                <p class="text-muted mb-1">@<%= @tweet_presenter.username %></p>
               <%= sanitize(@tweet_presenter.body_html(p_class: "fs-2 mb-1")) %>
                <p class="text-muted"><%= @tweet_presenter.tweet.created_at.strftime("%l:%M %p") %> · <%= @tweet_presenter.tweet.created_at.strftime("%b %d, %Y") %></p>

                <%= render "show_stats", tweet_presenter: @tweet_presenter %>
            </div>
        </div>

    </div>

    <%= render 'shared/tweet_form', form_submit_path: tweet_reply_tweets_path(@tweet_presenter.tweet), button_label: "Reply" %>

    <div id="reply_tweets">
        <%= render partial: "tweets/tweet", collection: @reply_tweets_in_presenter, as: :tweet_presenter %>
    </div>
</div>

<div class="col">
    <%= render 'shared/hashtag_sidebar' %>
</div>