config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end

  resources :bookmarks, only: :index
  resources :hashtags, only: [:index, :show], path: 'explore'

  resources :message_threads, only: :index, path: '/messages' do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  get '/dashboard', to: 'dashboard#index'
  get '/profile', to: 'profiles#show'
  put '/profile', to: 'profiles#update'

  resources :usernames, only: [ :new, :update ]
  resources :users, only: :show do
    resources :followings, only: [ :create, :destroy]
  end

  resources :notifications, only: :index
  get 'notifications/delete_all'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :actor, class_name: "User"
  belongs_to :tweet, optional: true
  
  VERBS = %w[ followed-me liked-tweet mentioned-me replied-me retweeted-tweet].freeze

  VERBS.each do |v|
    define_method("#{v.gsub("-", "_")}?") { v == verb }
  end
  validates :verb, presence: true, inclusion: { in: VERBS }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_action :authenticate_user!

    def index
        @notifications = current_user.notifications.includes(:actor, :tweet).reverse
        # @notifications_in_presenter = current_user.notifications.tweets.includes(:actor, :tweet, :user).reverse.map do |tweet|
        #     TweetPresenter.new(tweet: tweet, current_user: user)
    end

    def delete_all
        @delete_all = current_user.notifications.destroy_all
        flash[:alert] = "Notifications cleared"
        redirect_to notifications_path, status: :see_other
    end
end

app/views/notifications/index.html.erb
<div class="col-7">
    <div class="mb-2 d-flex justify-content-between align-items-center">
        <div>
            <%= link_to "Notifications", notifications_path, class: "fs-4 text-decoration-none text-black fw-semibold" %>
        </div>

        <div>
            <% if @notifications.any? %>
                <%= link_to "Clear all", notifications_delete_all_path, class: "text-danger", data: { "turbo-method": :get, turbo_confirm: "Are you sure?" } %>
            <% end %>
        </div>
    </div>

    <div id="tweets">
        <% @notifications.each do |notification| %>
            <% if notification.followed_me? %>
                <div class="notification p-2">
                    <% if notification.actor.avatar.present? %>
                        <%= link_to user_path(notification.actor) do %>
                            <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle mb-1" %>
                        <% end %>
                    <% else %>
                        <%= image_tag "user.png", size: "48x48", class: "rounded-circle mb-1" %>
                    <% end %>
                    <p class="mb-0"><span class="fw-bold"><%= notification.actor.display_name %></span> followed you</p>
                </div>
            <% elsif notification.liked_tweet? %>
                <div class="notification p-2">
                    <% if notification.actor.avatar.present? %>
                        <%= link_to user_path(notification.actor) do %>
                            <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle mb-1" %>
                        <% end %>
                    <% else %>
                        <%= image_tag "user.png", size: "48x48", class: "rounded-circle mb-1" %>
                    <% end %>
                    <p><span class="fw-bold"><%= notification.actor.display_name %></span> liked your tweet</p>
                    <p class="text-muted mb-1"><%= notification.tweet.body %></p>
                    <%= link_to "Show all", tweet_path(notification.tweet), class: "tweet-link mb-1" %>
                </div>
            <% elsif notification.mentioned_me? %>
                <div class="notification p-2">
                    <% if notification.actor.avatar.present? %>
                        <%= link_to user_path(notification.actor) do %>
                            <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle mb-1" %>
                        <% end %>
                    <% else %>
                        <%= image_tag "user.png", size: "48x48", class: "rounded-circle mb-1" %>
                    <% end %>
                    <p class="mb-0"><span class="fw-bold"><%= notification.actor.display_name %></span> mentioned you</p>
                    <p class="text-muted mb-1"><%= notification.tweet.body %></p>
                    <%= link_to "Show all", tweet_path(notification.tweet), class: "tweet-link mb-1" %>
                </div>
            <% elsif notification.replied_me? %>
                <div class="notification p-2">
                    <% if notification.actor.avatar.present? %>
                        <%= link_to user_path(notification.actor) do %>
                            <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle mb-1" %>
                        <% end %>
                    <% else %>
                        <%= image_tag "user.png", size: "48x48", class: "rounded-circle mb-1" %>
                    <% end %>
                    <p class="mb-0"><span class="fw-bold"><%= notification.actor.display_name %></span> replied you</p>
                    <p class="text-muted mb-1"><%= notification.tweet.body %></p>
                    <%= link_to "Show all", tweet_path(notification.tweet), class: "tweet-link mb-1" %>
                </div>
            <% elsif notification.retweeted_tweet? %>
                <div class="notification p-2">
                    <% if notification.actor.avatar.present? %>
                        <%= link_to user_path(notification.actor) do %>
                            <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle mb-1" %>
                        <% end %>
                    <% else %>
                        <%= image_tag "user.png", size: "48x48", class: "rounded-circle mb-1" %>
                    <% end %>
                    <p class="mb-0"><span class="fw-bold"><%= notification.actor.display_name %></span> retweeted your tweet</p>
                    <p class="text-muted mb-1"><%= notification.tweet.body %></p>
                    <%= link_to "Show all", tweet_path(notification.tweet), class: "tweet-link mb-1" %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

<div class="col">
    <div class="hashtag-sidebar p-2 rounded">
        <p class="p-2 fs-4 fw-bold mb-0">What's happening</p>
        <% Hashtag.limit(5).each do |hashtag| %>
            <div class="item p-2" data-controller="hashtag" data-url="<%= hashtag_path(hashtag) %>">
                <p class="fw-bold mb-0 fs-5"><%= hashtag.tag %> </p>
                <p class="text-muted fs-6 mb-0"><%= pluralize(hashtag.tweets.size, "Tweet") %> </p>
            </div>
        <% end %>
        <%= link_to "Show more", hashtags_path, class: "twitter-link p-2" %>
    </div>
</div>