config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end

  resources :bookmarks, only: :index
  resources :hashtags, only: [:index, :show], path: 'explore'

  resources :message_threads, only: :index, path: '/messages' do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  get '/dashboard', to: 'dashboard#index'
  get '/profile', to: 'profiles#show'
  put '/profile', to: 'profiles#update'

  resources :usernames, only: [ :new, :update ]
  resources :users, only: :show do
    resources :followings, only: [ :create, :destroy]
  end

  resources :notifications, only: :index
  get 'notifications/delete_all'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_tweets, through: :bookmarks, source: :tweet
  has_many :retweets, dependent: :destroy
  has_many :retweeted_tweets, through: :retweets, source: :tweet
  has_many :views
  has_many :viewed_tweets, through: :views, source: :tweet
  has_many :followings, dependent: :destroy
  has_many :following_users, through: :followings, source: :following_user
  has_many :reverse_followings, foreign_key: :following_user_id, class_name: "Following"
  has_many :followers, through: :reverse_followings, source: :user
  has_many :messages
  has_many :tweet_activities
  has_and_belongs_to_many :message_threads
  has_many :notifications, dependent: :destroy

  has_one_attached :avatar

  before_save :set_display_name, if: -> { username.present? && display_name.blank? }

  def set_display_name
    self.display_name = username.humanize
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        redirect_to profile_path if params[:id].to_i == current_user.id
        @user ||= User.find(params[:id])
        @tweet_presenters = @user.tweets.order(created_at: :desc).map do |tweet|
            TweetPresenter.new(tweet: tweet, current_user: @user)
        end
    end

end

app/views/users/_follow_button.html.erb
<%= turbo_frame_tag "follow_unfollow_button" do %>
    <% if user.followers.include?(current_user) %>
        <%= link_to "Unfollow", user_following_path(user, current_user.followings.find_by(following_user_id: user)), data: { "turbo-method": :delete }, class: "btn btn-outline-primary rounded-pill" %>
    <% else %>
        <%= link_to "Follow", user_followings_path(current_user, following_user_id: user.id), data: { "turbo-method": :post }, class: "btn btn-outline-primary rounded-pill" %>
    <% end %>
<% end %>

app/views/users/_profile_section.html.erb
<%= turbo_frame_tag "profile_section" do %>
    <div id="profile_section">
        <div class="mb-5">
            <%= link_to :back, class: "fs-4 text-decoration-none text-black fw-semibold" do %>
                <%= image_tag "back.png", size: "28x28", class: "me-4" %>
                <span style="position:relative; top: 2px;"><%= @user.username %></span>
                <span class="text-muted fs-6" style="position:relative; top: 2px;"><%= pluralize(@user.tweets.size, "Tweet") %></span>
            <% end %>
        </div>
        <div class="d-flex justify-content-between align-items-center mb-5">
            <div>
                <% if @user.avatar.present? %>
                    <%= image_tag @user.avatar, class: "rounded-circle", size: "150x150" %>
                    <%#= image_tag @user.avatar.variant(resize_to_limit: [500, 500]) %>
                <% else %>
                    <%= image_tag "user.png", class: "rounded-circle", size: "150x150" %>
                <% end %>
            </div>

            <% if controller_name == 'profiles' %>
                <div><%= button_tag 'Edit profile', class: "btn btn-outline-secondary rounded-pill w-100", data: { "bs-toggle": "modal", "bs-target": "#profileEditModal" } %></div>
            <% else %>
                <div>
                    <%= link_to message_threads_path(user_id: @user.id), class: "btn btn-outline-secondary rounded-pill" do %>
                        <%= image_tag 'envelope.png', size: '25x25' %>
                        Message
                    <% end %>
                    <%= render 'users/follow_button', user: @user, current_user: current_user %>
                </div>
            <% end %>
        </div>
        
        <div>
            <p class="fs-3 fw-semibold mb-0"><%= user.display_name %></p>
            <p class="fs-3 fw-semibold mb-0"><%= user.username %></p>
            <p><%= user.bio %></p>
            <div class="d-flex justify-content-start mb-3">
                <div class="me-4">
                    <%= image_tag "location.png", size: "23x23", class: "me-1" %>
                    <span class="text-muted"><%= user.location %></span>
                </div>
                <div class="me-4">
                    <%= image_tag "url.png", size: "23x23", class: "me-1" %>
                    <span class="text-muted"><%= link_to user.profile_url, user.profile_url, target: :_blank %></span>
                </div>
                <div class="me-4">
                    <%= image_tag "calendar.png", size: "23x23", class: "me-1" %>
                    <span class="text-muted"><%= user.created_at.strftime("%B %Y") %></span>
                </div>
            </div>
            <div class="d-flex justify-content-start">
                <div class="me-4"><span class="fw-semibold"><%= user.followings_count %></span> Following</div>
                <div class="me-4"><span class="fw-semibold"><%= user.followers_count %></span> Followers</div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_tweets_collection.html.erb
<div class="mt-3" id="tweets-collection">
    <%= render partial: "tweets/tweet", collection: @tweet_presenters, as: :tweet_presenter %>
</div>

app/views/users/show.html.erb
<div class="col-7">
    <div class="mb-5">
        
        <%= render "users/profile_section", user: @user, current_user: current_user %>

        <div id="tweets-collection">

            <%= render "users/tweets_collection", tweet_presenters: @tweet_presenters %>
        </div>
        
    </div>
</div>

<div class="col">
    <div class="hashtag-sidebar p-2 rounded">
        <p class="p-2 fs-4 fw-bold mb-0">What's happening</p>
        <% Hashtag.limit(5).each do |hashtag| %>
            <div class="item p-2" data-controller="hashtag" data-url="<%= hashtag_path(hashtag) %>">
                <p class="fw-bold mb-0 fs-5"><%= hashtag.tag %> </p>
                <p class="text-muted fs-6 mb-0"><%= pluralize(hashtag.tweets.size, "Tweet") %> </p>
            </div>
        <% end %>
        <%= link_to "Show more", hashtags_path, class: "twitter-link p-2" %>
    </div>
</div>

<% if controller_name == "profiles" %>
    <!-- Modal -->
    <div class="modal" id="profileEditModal" tabindex="-1" aria-labelledby="profileEditModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header border-bottom-0">
            <button type="button" class="btn-close mx-0 close-modal-btn" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%= form_with model: current_user, url: profile_path, data: { controller: 'tweet-form' }, class: "row g-3", locals: true, method: :put do |f| %>
                <form class="row g-3">
                    <div class="col-md-12">
                        <%= f.label :username, class: "form-label" %>
                        <%= f.text_field :username, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :display_name, class: "form-label" %>
                        <%= f.text_field :display_name, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :avatar, class: "form-label" %>
                        <%= f.file_field :avatar, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :email, class: "form-label" %>
                        <%= f.email_field :email, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :bio, class: "form-label" %>
                        <%= f.text_area :bio, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :location, class: "form-label" %>
                        <%= f.text_field :location, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :profile_url, "URL", class: "form-label" %>
                        <%= f.text_field :profile_url, class: "form-control" %>
                    </div>

                    <div class="col-md-12">
                        <%= f.submit "Update profile", class: "btn btn-twitter rounded-pill" %>
                    </div>
                </form>      
            <% end %>  
        </div>
        </div>
    </div>
    </div>
<% end %>