config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end

  resources :bookmarks, only: :index
  resources :hashtags, only: [:index, :show], path: 'explore'

  resources :message_threads, only: :index, path: '/messages' do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  get '/dashboard', to: 'dashboard#index'
  get '/profile', to: 'profiles#show'
  put '/profile', to: 'profiles#update'

  resources :usernames, only: [ :new, :update ]
  resources :users, only: :show do
    resources :followings, only: [ :create, :destroy]
  end

  resources :notifications, only: :index
  get 'notifications/delete_all'
end

app/views/shared/_aside.html.erb
<aside class="col side-navbar">

    <%= link_to dashboard_path, class: "d-flex align-items-center fs-5 px-3 mb-2" do %>
        <div class="px-2 py-2 rounded-circle">
            <%= image_tag 'twitter.png', width: "32" %>
        </div>
    <% end %>

    <%= link_to dashboard_path, class: "d-flex align-items-center fs-5 mb-2 #{nav_link_active?('dashboard')}" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3px"><%= image_tag 'home.png', width: "32" %></span>
            Home
        </div>
    <% end %>

    <%= link_to hashtags_path, class: "d-flex align-items-center fs-5 mb-2 #{nav_link_active?('hashtags')}" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3px"><%= image_tag 'hashtag.png', width: "32" %></span>
            Explore
        </div>
    <% end %>

    <%= link_to notifications_path, class: "#{ nav_link_active?('notifications') } d-flex align-items-center fs-5 mb-2" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3px"><%= image_tag 'notification.png', width: "32" %></span>
            Notifications
        </div>
    <% end %>

    <%= link_to message_threads_path, class: "d-flex align-items-center fs-5 mb-2 #{nav_link_active?('message_threads')}" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3px"><%= image_tag 'messages.png', width: "32" %></span>
            Messages
        </div>
    <% end %>

    <%= link_to bookmarks_path, class: "d-flex align-items-center fs-5 mb-2 #{nav_link_active?('bookmarks')}" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3px"><%= image_tag 'bookmark-aside.png', width: "32" %></span>
            Bookmark
        </div>
    <% end %>

    <%= link_to profile_path, class: "d-flex align-items-center fs-5 mb-2 #{nav_link_active?('profiles')}" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3px"><%= image_tag 'user.png', width: "32" %></span>
            Profile
        </div>
    <% end %>
    
    <div class="d-flex align-items-center fs-5 mb-2 py-3  px-4">
        <%= button_tag "Tweet", class: "btn btn-twitter btn-lg rounded-pill w-100", data: { "bs-toggle": "modal", "bs-target": "#tweetModal" } %>
    </div>

    <%= link_to "Sign out", destroy_user_session_path, class: "twitter-link", data: { turbo_method: :delete } %>
</aside>

<!-- Modal -->
<div class="modal" id="tweetModal" tabindex="-1" aria-labelledby="tweetModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        <button type="button" class="btn-close mx-0 close-modal-btn" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'shared/tweet_form', form_submit_path: tweets_path, button_label: "Tweet" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_hashtag_sidebar.html.erb
<div class="hashtag-sidebar p-2 rounded">
    <p class="p-2 fs-4 fw-bold mb-0">What's happening</p>
    <% Hashtag.limit(5).each do |hashtag| %>
        <div class="item p-2" data-controller="hashtag" data-url="<%= hashtag_path(hashtag) %>">
            <p class="fw-bold mb-0 fs-6"><%= hashtag.tag %> </p>
            <p class="text-muted fs-6 mb-0"><%= pluralize(hashtag.tweets.size, "Tweet") %> </p>
        </div>
    <% end %>
    <%= link_to "Show more", hashtags_path, class: "twitter-link p-2" %>
</div>

app/views/shared/_tweet_form.html.erb
<div class="tweet d-flex py-3 px-3">
    <div class="flex-shrink-0">
        <% if current_user.avatar.present? %>
            <%= image_tag current_user.avatar, size: "50x50", class: "rounded-circle" %>
        <% else %>
            <%= image_tag 'user.png', size: "48x48", class: "rounded-circle" %>
        <% end %>
    </div>
    <div class="flex-grow-1 ms-3">
        <%= form_with model: Tweet.new, url: form_submit_path, method: :post, data: { controller: 'tweet-form' } do |form| %>
            <%= form.text_area :body, placeholder: "What's happening?", class: "w-100 form-control tweet-input mb-4" %>

            <div class="d-flex justify-content-end">
                <%= form.submit button_label, class: "btn btn-twitter rounded-pill" %>
            </div>
        <% end %>
    </div>
</div>